### ISSUE TITLE
The automatically generated documentation is not updated

### ISSUE THREAD

**Issue by fridex** [thoth-station/nepthys#33]
**Describe the bug**

The automatic docs generation did not happen last time. I still see adviser v0.16.0, but the current release is v0.17.0.

**To Reproduce**

1. Go to https://thoth-station.ninja/docs/developers/adviser/
2. See docs v0.16.0
3. See error

**Expected behavior**

I should be able to see v0.17.0 docs generated.

**Comment by harshad16** [comment]
ah i will check on nepthys builds

**Comment by fridex** [comment]
> ah i will check on nepthys builds

Thanks!

Last time I did this locally, I spotted some issue with urllib3 in botocore when generating docs for thoth-storages. I don't recall if that is the issue maker (but might be an issue pointer).

**Comment by harshad16** [comment]
Following is the issue:
```
Warning: Permanently added 'github.com,140.82.113.3' (RSA) to the list of known hosts.
+ rm -rf thoth-station.github.io/docs/developers/
+ for repo in thamos adviser analyzer common lab package-extract python solver storages
+ mkdir -p thoth-station.github.io/assets/
+ mv thoth/thamos/_modules/ thoth/thamos/modules/
mv: cannot stat 'thoth/thamos/_modules/': No such file or directory
+ true
+ mv thoth/thamos/_images/ thoth/thamos/images/
mv: cannot stat 'thoth/thamos/_images/': No such file or directory
+ true
+ mv thoth/thamos/_sources/ thoth/thamos/sources/
mv: cannot stat 'thoth/thamos/_sources/': No such file or directory
+ true
+ mv 'thoth/thamos/_static/*' thoth-station.github.io/assets/
mv: cannot stat 'thoth/thamos/_static/*': No such file or directory
+ true
+ pushd thoth/thamos
/home/user/create_docs.sh: line 65: pushd: thoth/thamos: No such file or directory
```
can be found here: https://console-openshift-console.apps.ocp.prod.psi.redhat.com/k8s/ns/aicoe-prod-bots/pods/nepthys-1600387200-bll4j/logs
