### ISSUE TITLE
nepthys app runs are failing due host resolve issues.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/nepthys#56]
**Describe the bug**
git clone step in the nepthys , is having `github.com` host resolve issue.
```
+ for repo in thamos adviser analyzer common lab package-extract python solver storages
+ git clone --depth 1 https://github.com/thoth-station/thamos.git clones/thamos
Cloning into 'clones/thamos'...
fatal: unable to access 'https://github.com/thoth-station/thamos.git/': Could not resolve host: github.com
```

**Expected behavior**
A successful run of nepthys without any issues.

**Comment by goern** [comment]
is this a flake? sounds like OCP was not able to resolve hostnames?

**Comment by fridex** [comment]
I think this was related to ocp networking issues. The documentation is properly updated. Closing.

Thanks for the report! :+1:
